### ISSUE TITLE
Toevoegen van visuele indicatie dat je kunt scrollen

### ISSUE THREAD

**Issue by hay** [hay/kaartvandeliefde#18]
Zie voor voorbeeld in.beeldengeluid.nl

**Comment by mdepeffer** [comment]
Is gemaakt, weet alleen niet waar/hoe ik deze in de huidige opmaak moet zetten.

Zie http://dev.mitchdepeffer.nl/test3/test.php voor een voorbeeldje in het begin van elk thema (in nog oude code).

In de HTML zou dit komen na de ".container_content" in elke "contentHeader" (bovenste blok van een pagina):

```
<div class="container_scrollDown">
    <span>Scroll verder voor meer informatie!</span>
    <div class="arrow_down"></div>
</div>
```
