### ISSUE TITLE
Omtrek van Nederland in kaart

### ISSUE THREAD

**Issue by hay** [hay/kaartvandeliefde#22]

**Comment by shgzon** [comment]
Heel veel struggles i.v.m. niet kunnen vinden van Tiles (lijkt probleem te zijn in MapBox). Heb daarom voor gekozen om eenvoudig te houden en de standaard layer van Leaflet te gebruiken.

Hier staat de code die nodig is:
http://www.codeshare.io/OmPFP

Live voorbeeld: 
http://student.aii.avans.nl/cmd/shgzon/leaflet/
